services:
  - type: web
    name: cavity-detector-ai
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers 1 --threads 1 --timeout 300
    plan: free
